import type { MotionPlan } from "./schema";

export const defaultMotionPlan: MotionPlan = {
  id: "TimelinePreview",
  title: "Timeline Preview",
  concept: "A simple proof that prompt plans can render through reusable primitives.",
  format: {
    width: 1080,
    height: 1080,
    fps: 30,
    durationInFrames: 180,
    transparent: true,
  },
  style: {
    palette: ["#ffffff", "#ff4d2e", "#111111"],
    fonts: ["Inter"],
    motion: "snappy spring motion with a resolved final lockup",
    density: "balanced",
  },
  beats: [
    { id: "hook", start: 0, end: 45, intent: "establish the motion system" },
    { id: "build", start: 45, end: 120, intent: "show layered primitives" },
    { id: "resolve", start: 120, end: 180, intent: "hold a clean final frame" },
  ],
  tracks: [
    {
      id: "accent-sweep",
      type: "shape",
      start: 4,
      duration: 80,
      easing: "spring",
      shape: "rect",
      x: 540,
      y: 540,
      width: 760,
      height: 18,
      radius: 9,
      color: "#ff4d2e",
      opacity: 1,
      preset: "wipe",
    },
    {
      id: "headline",
      type: "text",
      start: 18,
      duration: 110,
      easing: "spring",
      text: "PLAN\nCOMPOSE\nREVIEW",
      x: 540,
      y: 500,
      width: 820,
      fontSize: 118,
      fontFamily: "Inter",
      fontWeight: 900,
      color: "#ffffff",
      align: "center",
      preset: "mask-reveal",
    },
    {
      id: "resolve-dot",
      type: "shape",
      start: 112,
      duration: 60,
      easing: "spring",
      shape: "circle",
      x: 540,
      y: 740,
      width: 28,
      height: 28,
      radius: 14,
      color: "#ffffff",
      opacity: 1,
      preset: "pulse",
    },
  ],
  reviewChecks: [
    "transparent-background",
    "safe-margins",
    "text-legibility",
    "contrast",
    "no-empty-frames",
    "resolved-final-frame",
  ],
};
