# The lakes of the CIA 2003 ethnoreligious map (Tharthar, Habbaniyah, Razzaza, the Mosul
# reservoir, ...), vectorised from the same LOC panel and georeferenced with the SAME fit as
# the mosaic (the affine stored in scripts/iraq-mosaic.json). For PickAColor's clean CIA
# redraw (builder M, Oct 5 2026).
#
#   uv run --with opencv-python-headless --with scipy --with numpy \
#     python scripts/build-iraq-lakes.py <panel.png>      (-> generated/components/iraqLakes.ts)
#
# Lake pixels = nearest-swatch "lake blue" (CIELAB, as in iraq-mosaic-vectorise.py), closed
# over the river lines and text that cross them, holes filled, components >= 250 px kept,
# contours smoothed (Gaussian sigma 1.5 px) and simplified (0.4 px). Output lon/lat rings;
# the component projects them with iraqShared's project().
import json
import sys

import cv2
import numpy as np
from scipy import ndimage as ndi

PANEL = sys.argv[1]
J = json.load(open("scripts/iraq-mosaic.json"))
A = np.array(J["source"]["fit"]["affine_px_to_lcc_km"]).T  # 3x2
R = 6371.0
P1, P2, LAT0, LON0 = np.radians([31, 36, 33, 44])
NN = np.log(np.cos(P1) / np.cos(P2)) / np.log(np.tan(np.pi / 4 + P2 / 2) / np.tan(np.pi / 4 + P1 / 2))
FF = np.cos(P1) * np.tan(np.pi / 4 + P1 / 2) ** NN / NN
RHO0 = R * FF / np.tan(np.pi / 4 + LAT0 / 2) ** NN


def px2ll(p):
    xy = np.column_stack([p[:, 0], p[:, 1], np.ones(len(p))]) @ A
    x, y = xy[:, 0], xy[:, 1]
    rho = np.sign(NN) * np.hypot(x, RHO0 - y)
    th = np.arctan2(x, RHO0 - y)
    return np.column_stack([np.degrees(LON0 + th / NN), np.degrees(2 * np.arctan((R * FF / rho) ** (1 / NN)) - np.pi / 2)])


img = cv2.imread(PANEL)
lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB).astype(np.float32)
SW = [(195, 169, 178), (222, 200, 176), (136, 123, 114), (187, 192, 193), (134, 142, 145), (171, 159, 182), (244, 243, 235), (152, 136, 136), (173, 179, 202)]
clab = cv2.cvtColor(np.array(SW, np.uint8)[None, :, ::-1], cv2.COLOR_BGR2LAB)[0].astype(np.float32)
L = ((lab[:, :, None, :] - clab[None, None]) ** 2).sum(-1).argmin(-1)
lake = L == 8
lake[1390:2048, 214:812] = False  # the legend box (its Turkoman swatch reads as lake blue)
lake = ndi.binary_closing(lake, iterations=4)
lake = ndi.binary_fill_holes(lake)
lake = ndi.binary_opening(lake, iterations=2)
lab_, n = ndi.label(lake)
areas = ndi.sum(np.ones_like(lab_), lab_, index=np.arange(1, n + 1))
keep = np.isin(lab_, np.nonzero(areas >= 250)[0] + 1)
cs, _ = cv2.findContours(keep.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
rings = []
for c in cs:
    p = c[:, 0, :].astype(float)
    if len(p) < 12:
        continue
    p = np.column_stack([ndi.gaussian_filter1d(p[:, i], 1.5, mode="wrap") for i in range(2)])
    a = cv2.approxPolyDP(p.astype(np.float32)[:, None, :], 0.4, True)[:, 0, :]
    ll = px2ll(a.astype(float))
    rings.append([[round(float(x), 5), round(float(y), 5)] for x, y in ll])
print(f"lakes: {len(rings)} rings, px areas {sorted(int(a) for a in areas if a >= 250)}")
with open("generated/components/iraqLakes.ts", "w") as f:
    f.write("// Generated by scripts/build-iraq-lakes.py — do not edit by hand.\n")
    f.write("// The lakes of the CIA 2003 ethnoreligious map (LOC 2003629031 panel), georeferenced with\n")
    f.write("// the mosaic's fit (scripts/iraq-mosaic.json). Rings in [lon, lat].\n")
    f.write(f"export const IRAQ_LAKES_LL: [number, number][][] = {json.dumps(rings)};\n")
